#!/usr/bin/env bash
set -euo pipefail

yadm checkout .

if [[ "$PREFIX" =~ '/data/data/com.termux/files/usr' ]] then

    termux-setup-storage

    pkg upgrade
    pkg in neovim mandoc lua-language-server

fi
