#!/usr/bin/env bash
set -euo pipefail

yadm checkout .

if [[ "$PREFIX" =~ '/data/data/com.termux/files/usr' ]] then

    termux-setup-storage

    pkg upgrade
    pkg i neovim mandoc lua-language-server clang tmux

fi
